### ISSUE TITLE
Null reference exception on timeout handler

### ISSUE THREAD

**Issue by desknotes** [br-automation-com/RFID-DotNET#1]
I've noticed that very often I get a null reference exception in the timeout handler, since the timer is disposed before in the **disconnect()** method.

`       
 internal void TimeoutTimer_Elapsed(object state)
        {
            Debug.WriteLine(DateTime.Now + " " + DateTime.Now.Millisecond + " Timeout timer");

            _retrys++;
            if (_retrys > 10)
            {
                _connected = false;
                try
                {
                    disconnect();
                }
                catch (Exception ex)
                {
                }
                if (OnException != null) OnException(excResponseTimeout);

            }
            TimeoutTimer.Change(Timeout.Infinite, 0);
        }
`

I don't understand why I get a timeout so often. I've set it to 250 ms, is it ok for a 5E9030?

thank you.

**Comment by stephan1827** [comment]
Should be fixes in latest commit
