### ISSUE TITLE
Errors when executing the .exe

### ISSUE THREAD

**Issue by jobled** [br-automation-com/RFID-DotNET#2]
I have got a first error when executing the projet, "Unhandled exception has occurred in your application  (...) Length cannot be less than zero :
![unhandledException](https://user-images.githubusercontent.com/64022004/104736413-30516c80-5743-11eb-9f71-b26dc35627fb.PNG)
The error file with more explanation :
[error.txt](https://github.com/br-automation-com/RFID-DotNET/files/5820931/error.txt)

And than, I guess it is related, when I click on Connect, I have a new fault : 
"Failed because 'PortName' cannot be set while the port is open'
![FailedPortOpen](https://user-images.githubusercontent.com/64022004/104736512-5e36b100-5743-11eb-930e-327654bf7381.PNG)

While I have a B&R RFID Reader, with the driver installed. I also managed to communicate and read a RFID Card with it through PuTTy, so the Reader and the port are OK.
Maybe I need to install something else ? The PanelPC is on Windows 7.

Thank you for your help, your project is already very nice.

**Comment by stephan1827** [comment]
I will look into this issue but can you please give me the following information

- What RFID are you using?
- Does the application start correct when the RFID is not connected?
- What COM port is assigned to the RFID reader?
- Is any other program (putty) accessing the RFID reader when you open the application?

**Comment by jobled** [comment]
The RFID I am using is the 5E9020.29 from a hygienic design Panel of B&R, so I can not disconnect it. However, when I try it on my own PC (without any RFID reader), I have the same first error, but next "Failed because Le port 'COM1' does not exist".
On the Panel PC, the RFID reader is on the COM3, and no other program is supposed to use it for now.

**Comment by stephan1827** [comment]
So I guess you installed "Version 1.1 for 5E9030.29"? I tried the setup on Windows 7 and it seems to run fine. Your issue seems to be related to the part that reads the INI file. This file should be located in C:\Program Files\BrAutomation\B&R RFID Reader Setup

Could you please post the content of that file here.

**Comment by jobled** [comment]
I downloaded the folder  RFID-DotNET-master\5E9030.29\RFID_USB\RFID_USB  in order to execute the RFID_USB.exe file.
Before that I copied the RFID.init of the same folder in C:\Program Files\BrAutomation\B&R RFID Reader Setup (However I had to create the last part of the path). So the .init content is the one of the original file : 

[CHK]
AutoConnect=True
SendBallon=True
SendKeys=True
SendKeysEnter=True

[RFID]
KeyMinLength=15
RefreshTimer=500
ResponseTimeout=2000

**Comment by stephan1827** [comment]
Can you try to run the setup file from here https://github.com/br-automation-com/RFID-DotNET/releases/tag/V1.1

**Comment by jobled** [comment]
I have the same error "length cannot be less than zero" when executing the .exe file, and when I click on continue, I have this new error : 
![errorBR_RFDI_Tester](https://user-images.githubusercontent.com/64022004/104886464-19d92a00-596a-11eb-932c-a32b9e9a9919.PNG)

Note that the pop up windows looks like this (miss some info comparing to your screenshot)
![popup_window](https://user-images.githubusercontent.com/64022004/104886641-5e64c580-596a-11eb-8af9-c93c6eede3a5.PNG)

Details of the new error ; 
[error_details.txt](https://github.com/br-automation-com/RFID-DotNET/files/5828590/error_details.txt)

**Comment by jobled** [comment]
Little precision, I am on Windows 7 Ultimate

**Comment by stephan1827** [comment]
That sounds like the DLL is missing. Does your installation folder look like this? What is the path to prgramm?

![image](https://user-images.githubusercontent.com/2972703/104887323-61ac8100-596b-11eb-8fe3-8e5a03047e77.png)

**Comment by jobled** [comment]
Okai the path was not right. Now it is working ! Thanks a lot.
I tried with a randow card, and it is detecting it but shows "false key reading". I guess I need to look through the code now to understand how to initialize my rfid card but if you have any tips I would be happy to read them.
![falseKeyReading](https://user-images.githubusercontent.com/64022004/104888783-86095d00-596d-11eb-8173-4b87967b1dd9.PNG)

Anyway thank you for you reactivity.

**Comment by stephan1827** [comment]
Great to hear that it works, can you share the path so I can try this on my end and make sure there is a proper error message. Take a look at KeyMinLength=15 in the INI file and adjust the value to the length of your keys.

**Comment by jobled** [comment]
Thank you !
The path that I used to work with was : 
C:\Program Files\BrAutomation\B&R RFID Reader Setup
instead of :
C:\Program Files (x86)\BrAutomation\B&R RFID Reader Setup

**Comment by stephan1827** [comment]
Strange, that path works for me...does the reader work when you adjust KeyMinLength?

**Comment by jobled** [comment]
Yes I adapt the KeyMinLength and now I can see the card ID
